export const WORDS_INIT: "WORDS_INIT" = "WORDS_INIT";
export const WORDS_ADD_FOLDER: "WORDS_" = "WORDS_";
export const WORDS_CHANGE_FOLDER: "WORDS_ADD_FOLDER" = "WORDS_ADD_FOLDER";
export const WORDS_DELETE_FOLDER: "WORDS_DELETE_FOLDER" = "WORDS_DELETE_FOLDER";
export const WORDS_ADD_WORD: "WORDS_ADD_WORD" = "WORDS_ADD_WORD";
export const WORDS_CHANGE_WORD: "WORDS_CHANGE_WORD" = "WORDS_CHANGE_WORD";
export const WORDS_DELETE_WORD: "WORDS_DELETE_WORD" = "WORDS_DELETE_WORD";
export const WORDS_CHANGE_WORD_FOLDER: "WORDS_CHANGE_WORD_FOLDER" =
  "WORDS_CHANGE_WORD_FOLDER";
